server:
  port: 8012

spring:
    application:
        name: config-service
    cloud:
        config:
              label: master
              server:
                    git:
                        skipSslValidation:  true
                        uri: https://github.com/bingo625/spring-cloud.git
                        searchPaths: config-repo
                        username:
                        password:
    profiles:
            active: -dev
eureka:
    client:
      serviceUrl:
          defaultZone: http://peer1:8000/eureka/
